#
# Copyright 2023, Colias Group, LLC
#
# SPDX-License-Identifier: BSD-2-Clause
#

[env]
RUST_TARGET_PATH = { value = "support/targets", relative = true }

[build]
target = "aarch64-sel4-microkit"

[unstable]
unstable-options = true
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
