[package]
name = "eth-driver"
version = "0.1.0"
authors = ["Ben Hamlin <hamlinb@galois.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
sel4cp.workspace = true
sel4-shared-ring-buffer.workspace = true

eth-driver-interface = { path = "./interface" }
