# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
  #pull_request:

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Compile simple sel4cp application
        uses: addnab/docker-run-action@v3
        with:
          image: podhrmic/rust-sel4-sel4cp-demo:latest
          options: -v ${{ github.workspace }}:/work
          run: |
            make compile
      - uses: actions/upload-artifact@v3
        if: success()
        with:
          name: loader
          path: build/loader.img
          retention-days: 1

  run-demo:
    runs-on: ubuntu-latest
    needs: compile-demo
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/download-artifact@v3
        with:
          name: loader
        run: |
          pwd
          ls -l
          ls -l build
      - name: Run simple sel4cp application
        uses: addnab/docker-run-action@v3
        with:
          image: podhrmic/rust-sel4-sel4cp-demo:latest
          options: -v ${{ github.workspace }}:/work
          run: |
            python3 test.py
      - uses: actions/upload-artifact@v3
        with:
          name: log
          path: log.txt
          retention-days: 1
